name: Repository Domain Scanner
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to scan'
        required: true


jobs:
  scanner:
    name: Public Domain Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Step 2 - Checkout GHA Repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.AMX_TOKEN }}
          path: './repository_for_scan'
          
      - name: Step 3 - Domain Scan
        run: |
          cd repository_for_scan
          ls
          docker image build -t ${{ inputs.repository }}:latest .
          docker save ${{ inputs.repository }}:latest -o image.tar
          tar -xvf image.tar
          pwd
          ls
          python3 ../src/domain-scanner.py pwd ${{ inputs.repository }}
          pwd 
          ls
      - name: Step X
        run: |
          cd repository_for_scan
          pwd
          ls
      - name: Step 4 - Save Results
        uses: actions/upload-artifact@v3
        with:
          name: domain-scan
          path: /home/runner/work/domain-scanner/domain-scanner/repository_for_scan/pwd.csv

