name: Setup-Python Tester
on:
  workflow_dispatch:

jobs:
  scanner:
    name: Public Domain Scanner
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.10'
